data1 = {
    "Visit 1 (G)": "Lately, I've been feeling pretty normal overall. I've had a couple of headaches here and there, but nothing too serious—just the kind that go away with some water or a nap. My appetite's been okay, and I've been sleeping decently. I get a little lightheaded if I stand up too fast, but I think that's just dehydration or something. Other than that, I've been going about my day like usual without any major issues.",
    "Visit 2 (M)": "Things have been a little off since I was last here. I've started waking up feeling kind of groggy, and it takes me longer to get moving. I've noticed my stomach feels weird after I eat, like a dull pressure or gurgling. Uhh, my joints feel stiffer than before too, especially my knees when I go up stairs. Nothing unbearable, but I'm just not feeling as steady or sharp as usual.",
    "Visit 3 (M)": "I don't know, something just feels off more consistently now. My headaches are lasting longer, and sometimes they feel like a pulsing behind my eyes. I've been waking up sweating, even when it's not hot, and I've started skipping meals because my stomach just turns at the idea of food. Uhh, I also noticed that I've been more irritable lately, like small things get under my skin fast. I wouldn't say I'm in pain exactly, but my body doesn't feel like it's on my side anymore.",
    "Visit 4 (M)": "The pressure in my head is more constant now, like there's a tight band around it. My stomach has started acting up every morning—it's hard to eat anything without feeling nauseous. Uhhh… also, my hands have been shaking slightly when I'm holding things, which is new. My sleep's broken up too, like I'll wake up two or three times a night and just lie there. I can still manage my day, but I feel like I'm running at half capacity.",
    "Visit 5 (B)": "I didn't sleep again. It's like my body won't shut down, and when it does, the dreams are loud. My joints feel like they've been packed with gravel, and every step stings. Uh… I tried eating toast this morning and it tasted like metal. There was this sound in my ears all night, like buzzing or someone whispering—wasn't real. My stomach kept moving like it had a heartbeat, but it's not supposed to do that, right?",
    "Visit 6 (B)": "The floor moved yesterday. I was just sitting and it started spinning like it was water. My mouth tastes like pennies sometimes. Uh... my head hurts in pulses, like thud, thud, thud, and then I forget what I was doing. My toes feel cold even with socks on. I keep seeing something in the corner of my eye, but it's not there when I look.",
    "Visit 7 (B)": "I didn't eat yesterday, or maybe I did, but I can't remember what. The lights are too bright now. Uh... sometimes I hear the wall clicking. My fingers feel like balloons filled with sand. I wrote my name and it didn't look right—looked like someone else wrote it.",
    "Visit 8 (B)": "I thought my arm was gone when I woke up. It was there but not there, you know? The fan said something to me, just for a second. Uh... my stomach feels like it's turning inside out. My knees won't lock, and I almost fell into the fridge. I think my teeth moved last night."
}

data2 = {
    "Visit 1 (M)": "Yeah, so things have been kind of off lately. My joints feel sore, mostly in the morning, and my stomach's been giving me some trouble after I eat. I wouldn't say it's super painful, but it's enough to notice. I've also been waking up more often in the night. Uhm, not sure if that's related, but I figured I should mention it.",
    "Visit 2 (M)": "So, I've had a few more of those stomach cramps—uhh, they've gotten a little sharper this week. Eating almost anything makes me feel kind of bloated and tired. I also feel like my muscles just don't recover anymore, like I go up a flight of stairs and my legs ache the rest of the day. I've been getting these weird headaches too, just like a dull pressure behind my eyes. Uhh, nothing crazy, but it's more than just annoying.",
    "Visit 3 (M)": "Things haven't really improved since the last visit. I'm feeling fatigued almost constantly now, and there's this stiffness in my lower back that makes it hard to get out of bed in the morning. Uhhh, and the headaches I mentioned? They're a little more intense now, and sometimes I see these floaters in my vision. I also noticed I've been more irritable lately—like, small things just set me off for no reason.",
    "Visit 4 (G)": "Actually, this past week's been a bit better. The stomach stuff's calmed down, and I've been eating normally again. I also started walking in the mornings and my joints feel looser. No headaches lately, which is nice. I don't feel 100%, but definitely closer to normal.",
    "Visit 5 (M)": "So, things are kind of backsliding again. Uhh, I've been getting this tight feeling in my chest—not really pain, more like pressure? My appetite's gone way down, and I've lost like five pounds without trying. My energy dipped too, especially in the afternoons—I almost nod off at my desk. And yeah, the joint pain is creeping back, mostly in my knees and elbows.",
    "Visit 6 (B)": "My hands are shaking a lot now. Uhhh… I can't really hold a pen right anymore. The headaches are back, but it's different—like, behind my ears? My vision's kinda... blurry sometimes. I saw a dog talking on the TV but it wasn't a cartoon.",
    "Visit 7 (B)": "There's this noise I keep hearing at night, like clicking, but no one else hears it. My stomach's real bad again, like twisting knots after I eat anything, even crackers. Uhhh... I walked into a door the other day, I didn't even see it. The air feels thick sometimes like I'm breathing jelly. I think someone moved the sky a little bit.",
    "Visit 8 (B)": "I woke up and couldn't feel my feet for a while. My jaw hurts when I talk too long. Uhh, I couldn't remember where I was this morning—like fully forgot. My teeth keep itching, which makes no sense. There was something crawling under my skin, I think it left."
}

data3 = {
    "Visit 1 (G)": "Lately I've been feeling alright, honestly. I still have the occasional headache in the evenings, but it's nothing I can't handle—it sort of comes and goes. My appetite's been decent and I'm sleeping through the night most days, which helps a lot. I've noticed a little stiffness in my knees when I first wake up, but once I'm up and moving, it usually goes away. Overall, I'd say I'm managing fine, just trying to keep up with my usual routine.",
    "Visit 2 (G)": "Things have been more or less steady. There are still a few moments where I get lightheaded if I stand up too fast, but it's not frequent. The muscle aches I mentioned before still show up in my legs after long walks, but I've just been taking breaks more often. I've been having a bit of trouble concentrating at work, though—not sure if it's related or just stress. Still, I'm able to get through the day without too much issue.",
    "Visit 3 (M)": "Uh, so it's been a little rougher lately. The headaches are sticking around longer, sometimes for most of the afternoon. I feel like I'm more tired, even when I sleep a full eight hours—just this heavy kind of fatigue. My stomach's been bothering me too, kinda like a dull ache after meals. I, uh, also noticed some tingling in my hands? It's not constant but it's weird.",
    "Visit 4 (M)": "I don't know, I've definitely felt worse this week. I've been waking up with this tight feeling in my chest—not pain, exactly, but uncomfortable. The joint pain in my elbows is worse, especially in the mornings; I have to stretch for a while before I can use my hands normally. Uh… sometimes my vision goes a little blurry when I move around too much, which is new. I also feel like I'm more forgetful, like I'll walk into a room and forget what I came for.",
    "Visit 5 (M)": "So... yeah, it's not great. I've been having these waves of nausea that come out of nowhere, like while I'm just sitting still. The fatigue has gotten deeper, like I'm dragging myself through each day. Uh, the pain in my knees has gotten worse too—I hear this grinding noise when I bend them. And my thoughts are kinda... fuzzy? Like I know what I want to say but it doesn't come out right sometimes.",
    "Visit 6 (M)": "It's been... uh, harder to keep things straight lately. My stomach's bloated all the time, even when I barely eat. I've got this weird buzzing feeling in my feet at night that keeps me from falling asleep. Sometimes I get dizzy just sitting down—like the room moves even when I'm still. Uh, and I've been forgetting people's names, even people I talk to all the time. It's frustrating.",
    "Visit 7 (B)": "I didn't eat the soup. It smelled like metal. My hands won't stop twitching, and there's this burning feeling in my chest but cold at the same time, like ice. I walked into the bathroom and just stood there, forgot what I was doing. My knees keep locking up, and I, uh... I tried to brush my teeth but the toothpaste felt wrong in my mouth.",
    "Visit 8 (B)": "Something is crawling behind my eyes. My stomach is a balloon but filled with knives. Can't feel my left toe, or maybe it's my right? The lights hum too loud now. I looked at the window and it blinked at me. There's buzzing in my ears that talks like a crowd but says nothing."
}

data4 = {
    "Visit 1 (M)": "So, things have been feeling kind of off the past couple of days. My stomach's been acting up—like, I get these cramps right after I eat, and sometimes I just don't even want to finish my meals. I've also been waking up a bit more tired than usual, even though I think I'm sleeping okay. Uhh, sometimes I feel this weird pressure in my head too—not quite a headache, but close. It's not terrible, but it's starting to wear on me a bit.",
    "Visit 2 (G)": "Actually, I think I've been feeling a little better since we last spoke. My appetite's mostly back, and the stomach cramps aren't really bothering me anymore. I've been sleeping more regularly and waking up without that heavy groggy feeling. My energy's been up—I even went on a short walk the other day and didn't feel completely drained. Still keeping an eye on things, but overall it feels like I'm getting back to normal.",
    "Visit 3 (M)": "So, it's kind of weird… the stomach stuff crept back in, but it's different now. Feels more like bloating that won't go away, especially at night. I also noticed my joints—like my knees and wrists—feel kind of stiff when I wake up, which wasn't really happening before. Uhh, also having some weird dreams lately. I don't know if that means anything, but I wake up feeling more restless again. It's like I'm in this back-and-forth pattern.",
    "Visit 4 (M)": "Yeah, I don't think things are improving right now. There's this persistent soreness in my lower back that just kind of sticks around all day. The headaches are more frequent, like this dull ache behind my eyes. Uhh, I'm also noticing I get dizzy sometimes when I stand up too fast, which never used to happen. Eating feels like a chore again—I'm not nauseous, just not hungry. It's frustrating, like I'm not fully sick but not really okay either.",
    "Visit 5 (M)": "I've been getting these random waves of exhaustion, like someone just flips a switch and I feel like lying down no matter what I'm doing. The bloating is worse, and now there's this weird gurgling in my gut that doesn't seem tied to meals. Uhh, I keep forgetting small things too, like where I left my phone or if I've taken my vitamins. My skin feels kind of sensitive, especially around my arms. It's not a rash, just like—almost like it's bruised under the surface?",
    "Visit 6 (M)": "Things still feel off, kind of steadily getting more uncomfortable. My knees have started to feel like they're grinding when I walk, especially in the mornings. Uhh, and I've noticed a tight feeling in my chest sometimes—not painful, just pressure that comes and goes. It's hard to focus at work, like my thoughts are slower or something. I don't think I'm forgetting major stuff, but I catch myself zoning out in the middle of conversations. That buzzing in my ears came back too—kind of faint, but definitely there.",
    "Visit 7 (B)": "Stomach hurts. Not sharp, just… full and hot. Knees feel like metal. I saw a fox on the balcony but there's no balcony. Uhh, I keep hearing this tapping when I sit still. Bread smells wrong lately—like rust or wires. Sometimes I talk and my tongue feels like it's stuck. Didn't eat dinner last night. Or was that lunch?",
    "Visit 8 (M)": "It's been a bit steadier lately, but not much better. I'm still getting the stomach weirdness, though not as sharp as before. I uhh, have been sleeping more, but I wake up still tired. My brain feels cloudy some days—it's hard to start tasks or finish them. The joint stuff hasn't gone away, and I think my grip strength might be weaker? It's just little things, but they pile up."
}

data5 = {
    "Visit 1 (G)": "So, I've been feeling alright lately. I've had a bit of tightness in my shoulders, mostly after I sit at my desk too long, but it goes away once I stretch. My sleep has been decent—some nights I wake up once or twice, but I can usually fall back asleep quickly. I've had a few mild headaches, mostly in the late afternoon, but nothing strong enough to stop me from doing things. My appetite is fine, and I've been eating pretty normally, no major changes there.",
    "Visit 2 (G)": "I'm still doing relatively okay. The headaches are a little more frequent now—like maybe every other day—but they're still manageable with water and rest. I've noticed some mild dizziness if I get up too quickly, though. My digestion seems slower than usual, but I haven't had any stomach pain or nausea. Energy levels are slightly lower than usual, but not enough to interfere with my day.",
    "Visit 3 (G)": "This past week I've been a little more tired than normal, but it could just be from stress. My legs feel a little achy by the end of the day, especially around my knees. Nothing sharp, just a dull sort of pressure. I did have one night where I woke up sweating, but that didn't happen again. Other than that, I've been able to keep up with work and errands just fine.",
    "Visit 4 (M)": "So, uhh, lately it's been tougher to focus during the day. I'll start a task and sort of…forget what I was doing halfway through. The headaches are stronger now—more of a throbbing pain behind my eyes, sometimes lasting a few hours. My stomach has been acting up too; there's this weird churning feeling, especially after I eat. I've also been waking up in the middle of the night with this kind of anxious energy I can't shake.",
    "Visit 5 (M)": "I'm starting to feel more off than before. There's this heaviness in my chest—not pain, exactly, but like I can't breathe in fully sometimes, especially at night. Uhh, my muscles ache almost all the time now, mostly in my lower back and thighs. I've had trouble eating much lately, just don't feel hungry and sometimes food tastes…weird? Also, my sleep's been awful—waking up four or five times, sometimes with this tight, panicky feeling in my chest.",
    "Visit 6 (B)": "I dunno, things are different. My hands shake now, a little, like when I'm holding a glass it rattles. The headache's all day, almost like a helmet squeezing my brain. Umm… sometimes I hear this low buzzing, like, in the walls? Food's hard to keep down, and my stomach keeps making these gurgling sounds that feel wrong. I keep dreaming about water flooding the room, but I wake up dry.",
    "Visit 7 (B)": "Couldn't sleep again. My arms feel like they're made of glass. Every time I turn my neck it feels like gravel inside. Uhhh, I forgot where I put my shoes yesterday and found them in the fridge. There's a taste like metal in my mouth all day, even when I brush my teeth.",
    "Visit 8 (B)": "It's like my skin doesn't fit right. My joints pop when I walk, like, pop-pop-pop, louder than they should. There was a bird outside yesterday, but I think it was talking to me. Uhh, when I bend over I see spots—blue, red, flickering. I didn't eat yesterday but I'm not hungry."
}

data6 = {
    "Visit 1 (M)": "Yeah, so lately I've been feeling kinda off—my joints feel stiffer in the morning, and there's this sort of dull ache that stays with me most of the day. It's not awful, but it's been messing with my routine, especially getting out of bed or walking up stairs. My stomach has also been a bit weird—some bloating, maybe mild nausea after I eat, but not every time. I've also been more tired than usual, like, even after sleeping eight hours, I still feel worn out. Uhh, I figured it might just be stress or something, but it's been happening more days than not.",
    "Visit 2 (M)": "Things have, uhh, gotten a little worse since last time. The pain in my joints is sharper now, especially in my knees and wrists—it's not just in the morning anymore. I've also had a few headaches that start behind my eyes and kind of throb, especially in the afternoons. My stomach's acting up more consistently too—like a tightness, and sometimes I get random cramping even when I haven't eaten. I've also noticed I'm forgetting small things—like leaving the stove on or misplacing my keys a lot more. I don't know, it's probably nothing serious, but it's starting to get annoying.",
    "Visit 3 (M)": "So, umm, things are still getting worse. I wake up a couple times at night now because my joints hurt, and sometimes I can't fall back asleep. The headaches are hitting more often—almost daily now, and they last longer than before. I've been feeling a bit queasy every morning, and sometimes I get this weird pressure in my chest—not like pain, but like it's harder to take a full breath. I'm also having trouble focusing—like I'll read something and forget it right away. Uhh, it's frustrating because I can't really function the same way I used to, and it's starting to impact my work.",
    "Visit 4 (B)": "Okay, yeah, it's—uh—it's bad now. My joints just, like, lock up? Not always, but I'll be walking and then just stop 'cause I can't move. The headaches feel like they're drilling into my skull, and light makes them worse. My stomach hurts even when I don't eat, and sometimes I smell metal? Like, there's no metal, but it's there. I saw a crow yesterday that spoke French, or maybe it was my neighbor.",
    "Visit 5 (B)": "I didn't sleep at all last night. Every time I closed my eyes, I heard static, and I felt like something was crawling on my skin. My knees feel like they're filled with glass. My hands shake when I try to hold things, and I dropped my toothbrush like three times this morning. Um, I also—what was I saying? Right, right, I think the floor hums sometimes.",
    "Visit 6 (B)": "My stomach feels like there's a snake inside it, twisting. I tried eating toast, but it tasted like pennies. My head keeps pounding, and I see little flashes sometimes, like someone's taking photos. I couldn't remember where I was earlier today, I stood in the hallway and just stared. Uhh, and I think my TV said my name yesterday, even though it was off.",
    "Visit 7 (M)": "I don't think I'm as bad as before, but I'm still not great. The headaches aren't as intense, but they come in waves—like, I'll be fine, and then boom, pressure right behind the eyes. My joints still ache, mostly in the morning and if I sit too long. I'm eating a bit more now, though my stomach still gets that weird tight feeling after meals. Memory's better too, I think—I only forgot my PIN once this week.",
    "Visit 8 (M)": "There's been a little improvement, I guess. The pain is still there, but it doesn't hit as hard or as often. My sleep's more regular—still waking up sometimes, but not every night. I feel like I can concentrate a bit better, like I actually finished a book this week. Uhh, still have random nausea, but I can at least eat a full meal now without feeling awful."
}

data7 = {
    "Visit 1 (G)": "Lately I've been feeling mostly fine. My appetite is back to normal, and I've been sleeping a solid seven to eight hours. The aches in my knees that I mentioned last time have eased up a lot—maybe it was the weather? I still get a bit of heartburn after eating spicy food, but nothing out of the ordinary. Overall, I'd say I'm doing okay, just a little tired here and there.",
    "Visit 2 (M)": "So, things aren't quite as good now. I've been waking up with this dull pain in my lower back, and it sort of lingers through the day. Uh, also, I've noticed my energy's been dipping—like, I get winded after just walking a couple of blocks. My appetite's okay, I guess, but food hasn't been tasting the same. I don't know, maybe I'm just worn out or something.",
    "Visit 3 (M)": "I'm still not feeling right, and now there's this weird pressure in my head sometimes. Like, not a full-blown headache, but a buzzing kind of tightness? Uh, hard to describe exactly. I've also started having trouble falling asleep, and when I do sleep, I wake up sweaty. It's not terrible, but it's, um, it's not great either.",
    "Visit 4 (M)": "Things have definitely dipped more since last time. My stomach's been acting up—some bloating, mild cramping, and just feeling... off. Uh, I've also noticed my joints are stiff in the mornings, like it takes a good while to loosen up. There's this occasional chest flutter that kind of freaks me out, but it passes quickly. I haven't told anyone yet, but I've been zoning out sometimes when people talk to me.",
    "Visit 5 (B)": "It's worse now. My head hurts all day. My fingers go numb, especially in the morning. Can't sleep. Uh... I keep smelling something burnt, but no one else smells it. My cat told me not to eat the cereal, and I listened. It's hard to think. I forgot how to tie my shoes the other day.",
    "Visit 6 (M)": "So, I think I'm a little better than last time. The headaches aren't constant anymore—more like they come and go. Uh, still having issues with sleep though. I wake up a lot during the night, and my mouth's super dry in the morning. My stomach's still unpredictable, but I've been eating softer foods and that helps a bit.",
    "Visit 7 (M)": "The dizziness came back yesterday—felt like the room tilted for a second. Uh, that hasn't happened in a while. My joints are stiff again, especially in the evening. I've also been dropping things more, like my grip's weaker than usual. Sometimes I blink and forget where I am for a second—it's quick, but weird.",
    "Visit 8 (G)": "I'm actually feeling a bit more like myself again. Energy levels are better and I'm back to walking without getting too tired. The pressure in my head is mostly gone, and I've had a few full nights of sleep. I've been drinking more water and cutting out caffeine, and I think it's helping. Still keeping an eye on a few symptoms, but I'd say this is the best I've felt in weeks."
}

data8 = {
    "Visit 1 (M)": "Yeah, so I've been feeling kind of off the past couple days. My stomach's been giving me trouble—sort of a dull ache most of the time, but then it'll cramp up real bad for a few minutes. I also had a couple nights where I just couldn't sleep right, like I kept waking up sweaty and just... unsettled. My head's been pounding on and off, but I figured it's maybe the weather or something. Uhm, I don't know, I've just been really tired even though I'm not doing much lately.",
    "Visit 2 (M)": "Okay, so, things haven't really improved since last time. I still have that stomach pain, but now it feels like it's sort of bloated and tight? I don't know, like pressure. And my head—uh, it just hurts behind my eyes, and it's worse when I stand up or move too fast. I started forgetting little things too, like I was brushing my teeth and totally spaced out halfway through. Honestly, it's... uh... weird.",
    "Visit 3 (B)": "It's worse now. My hands shake sometimes, and I can't grip stuff right. My stomach's a balloon. Hurts when I breathe in. I heard a noise last night, but there was nothing there. It was like the floor was humming, but, umm... the floor don't hum, right?",
    "Visit 4 (B)": "I didn't sleep again. Like I closed my eyes and then, boom, it was morning but I was still tired? I coughed and I tasted metal. My toes feel numb now. Something's crawling around in my gut, I swear it. The moon last night looked like it was watching me.",
    "Visit 5 (M)": "Things settled a bit since the last time, I think. The stomach stuff still comes and goes, but it's not constant now. My head's still kinda heavy, but not spinning like before. Uhhh, I still forget things sometimes, like names or what I walked into a room for. Appetite's weird though—some days I eat too much, some days I forget to eat.",
    "Visit 6 (M)": "Yeah, I've been trying to keep track of everything, and it's kinda all over the place. The bloating's back, especially after I eat bread or dairy, I think. Still getting tired real fast, and sometimes my joints just ache for no reason. Uhm, I had this thing where my vision blurred for a few seconds, but it went away. Not sure if that's connected or just random.",
    "Visit 7 (M)": "I'm not sure what's going on anymore. Things seem better and worse at the same time, if that makes sense? Like, I'll feel okay one hour and then the next I just feel like I'm floating. My skin's been itchy too, but there's no rash. Uhh, sometimes it feels like my body's just not syncing up with itself.",
    "Visit 8 (G)": "Hey, I think I'm doing alright these days. That weird stomach pressure has mostly gone away, and I've been sleeping a lot better. No major headaches recently either. I've been walking more, and that seems to help with the fatigue. Honestly, I feel more clearheaded than I have in weeks."
}

data9 = {
    "Visit 1 (M)": "So, I've been feeling kinda off lately. It's not terrible, but there's this dull ache in my lower back that's been sticking around for a few days. I also noticed some bloating after meals and a bit of nausea here and there, but nothing too strong. Oh, and I've been more tired than usual—like, just brushing my teeth makes me want to sit down after. Uh, I don't know if it's the weather or something I ate, but I figured it was worth mentioning.",
    "Visit 2 (G)": "Honestly, things have been looking up since my last visit. That back pain I had is almost completely gone, and my digestion seems smoother too. I've had more energy and have been sleeping better at night. No nausea lately either, which is a relief. I've even started going for short walks again—feels good to be getting back to normal.",
    "Visit 3 (M)": "Things dipped a little again. I've been waking up with some stomach cramps, especially in the early morning. The fatigue is creeping back too—like, I can still get things done, but it just takes more effort. Uh, I also noticed this tight feeling in my chest sometimes, especially when I'm lying down. It's not painful exactly, just… weird. I thought maybe it was stress or something.",
    "Visit 4 (M)": "It's kinda up and down right now. Still having those cramps, and now they're sometimes joined by this fluttery feeling in my chest. I, uh, sometimes feel a little disoriented if I stand up too fast. Appetite's been shrinking too—food just doesn't sound that good most of the time. And there's this vague soreness in my joints, like everything's a bit stiffer than usual. Not terrible, just annoying.",
    "Visit 5 (B)": "Didn't sleep at all last night. My arms feel heavy, like someone tied bricks to them. Stomach's been gurgling nonstop and I keep getting these sharp jabs near my ribs. Uhhhh, I tried making coffee and forgot I already made some. Felt like bugs were crawling inside my feet this morning. It's getting hard to tell if I'm dreaming or awake sometimes.",
    "Visit 6 (B)": "My head feels like cotton. Like, thick, wet cotton. I uh… I couldn't remember how to turn on the shower yesterday, just stood there looking at the faucet. My joints keep popping—like popcorn—but they hurt too. Stomach hurts even when I don't eat, and then when I do eat, it's worse. Something in the ceiling whispered, but I don't know what it said.",
    "Visit 7 (B)": "There was blood in my stool this morning. It smelled like metal. I didn't recognize my own handwriting when I tried to make a grocery list—uhhh, I think I wrote 'feather time' three times. I can't sit for long, my back seizes up. I keep hearing a buzzing that no one else hears. I'm not sure what day it is, or if this is still April.",
    "Visit 8 (M)": "I think I'm doing a little better now, compared to last week. The sharp pains have dulled down, and I haven't had any more bleeding. I still feel, uhh, kinda foggy, like there's a delay between my thoughts and speaking. But I'm eating small meals again and holding them down. There's still some chest tightness now and then, but it's not constant anymore."
}

data10 = {
    "Visit 1 (G)": "Yeah, so overall I've been feeling okay lately. I still get that dull ache in my lower back every now and then, but it's nothing I can't manage. My appetite's been stable, and I've been sleeping better than I was a few weeks ago. I have noticed a little bit of stiffness in my fingers in the morning, but it goes away after I move around a bit. Energy-wise, I feel more or less normal, and I've been able to keep up with my daily walks.",
    "Visit 2 (M)": "I've been feeling a little off the past few days. The back pain has started to get sharper, especially when I bend or twist. Uh, I also noticed my hands are staying stiff longer in the morning, and sometimes they feel kind of numb. My sleep's gotten worse too—keep waking up a few times during the night for no real reason. I don't feel as hungry as before, and sometimes I just skip breakfast without realizing.",
    "Visit 3 (M)": "It's getting harder to stay focused during the day. My head feels foggy, and sometimes I lose track of what I'm doing. Uhh, the joint pain is spreading to my knees now, and it feels like they're grinding or something. I've also been getting headaches more often—kind of a pulsing pain right at the front. I tried going for a walk yesterday, and I had to stop halfway through 'cause I felt too tired.",
    "Visit 4 (M)": "I've been waking up drenched in sweat, even though the room's not hot at all. It's, um, kind of unnerving. The headaches are stronger, and my stomach's been bothering me—feels tight and queasy after I eat. I've also noticed I'm forgetting simple things, like where I put my keys or what I was saying mid-sentence. Sometimes I feel like I'm watching everything from behind a screen or something—it's hard to explain.",
    "Visit 5 (B)": "Uhhh... the light hurts. It's... it's too loud in the kitchen. My knees don't bend right, like they're made of gravel or, or rubber maybe. There's something moving behind my eyes when I try to sleep. I saw a rabbit last night but I don't own a rabbit. My skin feels like it's buzzing.",
    "Visit 6 (M)": "I feel a little less... jumbled than I did last time, but the aches are still pretty bad. My lower back locks up if I sit too long, and I've been getting muscle twitches in my legs. I, uh, think the headaches aren't as sharp, but they come more frequently now. I'm still forgetting things, but it's more like names and appointments this time. My stomach is still uneasy, mostly after meals.",
    "Visit 7 (M)": "So, I'm still getting that weird out-of-body feeling every now and then. It's not as intense, but it catches me off guard. Uhh, my fingers get numb when I type or hold a pen for too long, and the pain in my knees is back again. I also noticed some ringing in my ears that wasn't there before. I've been keeping track of all this in a notebook, but I forgot where I put it yesterday.",
    "Visit 8 (M)": "It's been a strange week. The headaches now feel like pressure, like something's pressing from inside out. My appetite's gotten worse—just thinking about food sometimes makes me feel sick. Uhh, I've also been talking slower, or at least people keep asking me to repeat things. There's still that buzzing in my hands at night, but it's more like a vibration now than tingling. I haven't been able to finish a book or even a TV episode lately—can't concentrate."
}

all_data = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10]
input_voice = [
    'concatenated_audio_F03.wav',
    'concatenated_audio_M05.wav',
    'concatenated_audio_M03.wav',
    'concatenated_audio_F01.wav',
    'concatenated_audio_F04.wav',
    'concatenated_audio_M04.wav',
    'concatenated_audio_M01.wav',
    'concatenated_audio_M02.wav',
    'old_lady.mp3',
    '',
]